import { ICar } from '@/types/car.types';

export const RAW_CARS: any[] = [
  // ── 20 FOR SALE CARS ────────────────────────────────────────────────────────
  {
    _id: 'fb-sale-1',
    slug: 'toyota-premio-f-ex-package-2021',
    title: 'Toyota Premio F-EX Package 2021',
    brand: 'Toyota',
    model: 'Premio',
    year: 2021,
    condition: 'certified',
    color: 'Pearl White',
    price: 3850000,
    salePrice: 3850000,
    mileage: 24000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    seats: 5,
    doors: 4,
    location: 'Dhaka',
    description: 'Fresh import Japan auction grade 4.5. Toyota Safety Sense, beige interior, push start, power seats.',
    coverImage: 'https://images.unsplash.com/photo-1590362891988-f77804703058?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1590362891988-f77804703058?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'sale',
    status: 'published',
    rating: 4.9,
    totalReviews: 8,
    isFeatured: true,
    features: ['Push Start', 'Leather Seats', 'Rear Camera'],
    amenities: ['Air Conditioning', 'Power Steering'],
  },
  {
    _id: 'fb-sale-2',
    slug: 'honda-civic-rs-turbo-2022',
    title: 'Honda Civic RS Turbo 2022',
    brand: 'Honda',
    model: 'Civic',
    year: 2022,
    condition: 'used',
    color: 'Sonic Gray',
    price: 4950000,
    salePrice: 4950000,
    mileage: 18500,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    seats: 5,
    doors: 4,
    location: 'Gulshan',
    description: 'Honda Civic RS Turbo with Bose sound system, red interior stitching, Honda Sensing, mint condition.',
    coverImage: 'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'sale',
    status: 'published',
    rating: 5.0,
    totalReviews: 12,
    isFeatured: true,
    features: ['Sunroof', 'Turbocharger', 'Bose Audio'],
    amenities: ['Climate Control', 'Keyless Entry'],
  },
  {
    _id: 'fb-sale-3',
    slug: 'bmw-3-series-320i-m-sport-2023',
    title: 'BMW 3 Series 320i M-Sport 2023',
    brand: 'BMW',
    model: '3 Series',
    year: 2023,
    condition: 'new',
    color: 'Portimao Blue',
    price: 9800000,
    salePrice: 9800000,
    mileage: 4200,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    seats: 5,
    doors: 4,
    location: 'Banani',
    description: 'Brand new official dealership unit. M Sport aerodynamic package, curved digital cockpit, sunroof.',
    coverImage: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'sale',
    status: 'published',
    rating: 4.9,
    totalReviews: 6,
    isFeatured: true,
    features: ['M Sport Package', 'Navigation', 'Curved Display'],
    amenities: ['Apple CarPlay', 'Wireless Charging'],
  },
  {
    _id: 'fb-sale-4',
    slug: 'mercedes-benz-c200-2022',
    title: 'Mercedes-Benz C-Class C200 2022',
    brand: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2022,
    condition: 'used',
    color: 'Obsidian Black',
    price: 11500000,
    salePrice: 11500000,
    mileage: 14000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    seats: 5,
    doors: 4,
    location: 'Dhaka',
    description: 'Mild hybrid EQ Boost, AMG Line dynamic body styling, panoramic glass roof, Burmester 3D surround sound.',
    coverImage: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'sale',
    status: 'published',
    rating: 5.0,
    totalReviews: 14,
    isFeatured: true,
    features: ['Burmester 3D', 'Panoramic Roof', 'AMG Styling'],
    amenities: ['Ambient Lighting', 'Leather Seats'],
  },
  {
    _id: 'fb-sale-5',
    slug: 'toyota-land-cruiser-prado-tx-l-2020',
    title: 'Toyota Land Cruiser Prado TX-L 2020',
    brand: 'Toyota',
    model: 'Land Cruiser Prado',
    year: 2020,
    condition: 'certified',
    color: 'Black Pearl',
    price: 14500000,
    salePrice: 14500000,
    mileage: 38000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    seats: 7,
    doors: 5,
    location: 'Uttara',
    description: 'TX-L 7-seater luxury SUV, beige leather upholstery, sunroof, 360-degree cameras, Modellista body aero kit.',
    coverImage: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'sale',
    status: 'published',
    rating: 4.8,
    totalReviews: 9,
    isFeatured: true,
    features: ['7 Seater', '4WD', '360 Camera', 'Sunroof'],
    amenities: ['Rear AC', 'Modellista Kit'],
  },
  {
    _id: 'fb-sale-6',
    slug: 'hyundai-tucson-turbo-2023',
    title: 'Hyundai Tucson 1.6 Turbo AWD 2023',
    brand: 'Hyundai',
    model: 'Tucson',
    year: 2023,
    condition: 'new',
    color: 'Titan Gray',
    price: 5900000,
    salePrice: 5900000,
    mileage: 5000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'SUV',
    seats: 5,
    doors: 5,
    location: 'Dhanmondi',
    description: 'Modern geometric parametric styling, panoramic sunroof, digital cluster, electronic push gear selector.',
    coverImage: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'sale',
    status: 'published',
    rating: 4.9,
    totalReviews: 11,
    isFeatured: true,
    features: ['Panoramic Sunroof', 'AWD', 'Digital Cockpit'],
    amenities: ['Heated Seats', 'Wireless Charger'],
  },
  {
    _id: 'fb-sale-7',
    slug: 'audi-a4-40-tfsi-s-line-2022',
    title: 'Audi A4 40 TFSI S-Line 2022',
    brand: 'Audi',
    model: 'A4',
    year: 2022,
    condition: 'used',
    color: 'Glacier White',
    price: 7600000,
    salePrice: 7600000,
    mileage: 21000,
    fuelType: 'Petrol',
    transmission: 'Dual-Clutch',
    bodyType: 'Sedan',
    seats: 5,
    doors: 4,
    location: 'Chattogram',
    description: 'Audi Virtual Cockpit, S-Line sport package, Matrix LED headlights, dynamic turn indicators.',
    coverImage: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'sale',
    status: 'published',
    rating: 4.8,
    totalReviews: 7,
    isFeatured: false,
    features: ['Virtual Cockpit', 'Matrix LED', 'S-Line'],
    amenities: ['Sport Seats', 'Bang & Olufsen'],
  },
  {
    _id: 'fb-sale-8',
    slug: 'nissan-x-trail-e-power-2023',
    title: 'Nissan X-Trail e-POWER 4WD 2023',
    brand: 'Nissan',
    model: 'X-Trail',
    year: 2023,
    condition: 'certified',
    color: 'Diamond Black',
    price: 6400000,
    salePrice: 6400000,
    mileage: 11000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'SUV',
    seats: 7,
    doors: 5,
    location: 'Dhaka',
    description: 'Innovative e-POWER electric motor drive, e-4ORCE all-wheel control system, Nappa leather, HUD display.',
    coverImage: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'sale',
    status: 'published',
    rating: 4.9,
    totalReviews: 5,
    isFeatured: false,
    features: ['e-POWER EV Drive', 'HUD Head-up Display', 'Nappa Leather'],
    amenities: ['ProPILOT', '360 Camera'],
  },
  {
    _id: 'fb-sale-9',
    slug: 'toyota-camry-hybrid-2022',
    title: 'Toyota Camry Hybrid Premium 2022',
    brand: 'Toyota',
    model: 'Camry',
    year: 2022,
    condition: 'used',
    color: 'Silver Metallic',
    price: 6800000,
    salePrice: 6800000,
    mileage: 19000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    seats: 5,
    doors: 4,
    location: 'Gulshan',
    description: 'Executive sedan with ultra-smooth hybrid drive. JBL premium audio, ventilated leather seats, head-up display.',
    coverImage: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'sale',
    status: 'published',
    rating: 4.9,
    totalReviews: 15,
    isFeatured: true,
    features: ['JBL Sound', 'Ventilated Seats', 'Radar Cruise Control'],
    amenities: ['Power Rear Sunshade', 'Wireless Charger'],
  },
  {
    _id: 'fb-sale-10',
    slug: 'honda-cr-v-ex-l-turbo-2022',
    title: 'Honda CR-V EX-L Turbo 2022',
    brand: 'Honda',
    model: 'CR-V',
    year: 2022,
    condition: 'certified',
    color: 'Crystal Black',
    price: 5400000,
    salePrice: 5400000,
    mileage: 23000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'SUV',
    seats: 5,
    doors: 5,
    location: 'Uttara',
    description: 'Spacious family SUV with turbocharged efficiency. Power tailgate, leather interior, Honda Sensing suite.',
    coverImage: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'sale',
    status: 'published',
    rating: 4.8,
    totalReviews: 10,
    isFeatured: false,
    features: ['Turbo Engine', 'Power Tailgate', 'Honda Sensing'],
    amenities: ['Sunroof', 'Dual Zone Climate'],
  },
  {
    _id: 'fb-sale-11',
    slug: 'bmw-x5-xdrive40i-2022',
    title: 'BMW X5 xDrive40i M-Sport 2022',
    brand: 'BMW',
    model: 'X5',
    year: 2022,
    condition: 'used',
    color: 'Mineral White',
    price: 18500000,
    salePrice: 18500000,
    mileage: 16000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'SUV',
    seats: 5,
    doors: 5,
    location: 'Gulshan',
    description: 'Luxury executive SAV with panoramic Sky Lounge LED roof, Harman Kardon surround sound, air suspension.',
    coverImage: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'sale',
    status: 'published',
    rating: 5.0,
    totalReviews: 18,
    isFeatured: true,
  },
  {
    _id: 'fb-sale-12',
    slug: 'mercedes-benz-gle450-2022',
    title: 'Mercedes-Benz GLE 450 4MATIC 2022',
    brand: 'Mercedes-Benz',
    model: 'GLE-Class',
    year: 2022,
    condition: 'certified',
    color: 'Selenite Grey',
    price: 21000000,
    salePrice: 21000000,
    mileage: 12000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'SUV',
    seats: 7,
    doors: 5,
    location: 'Banani',
    description: '7-seater luxury flagship SUV. AMG line exterior, Burmester sound, multi-beam LED, MBUX interior assist.',
    coverImage: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'sale',
    status: 'published',
    rating: 5.0,
    totalReviews: 21,
    isFeatured: true,
  },
  {
    _id: 'fb-sale-13',
    slug: 'toyota-harrier-z-leather-2021',
    title: 'Toyota Harrier Z Leather Package 2021',
    brand: 'Toyota',
    model: 'Harrier',
    year: 2021,
    condition: 'certified',
    color: 'Precious Black Pearl',
    price: 7400000,
    salePrice: 7400000,
    mileage: 26000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'SUV',
    seats: 5,
    doors: 5,
    location: 'Dhanmondi',
    description: 'JBL 9-speaker audio, electrochromic dimming panoramic roof, brown leather interior, Modellista aero kit.',
    coverImage: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'sale',
    status: 'published',
    rating: 4.9,
    totalReviews: 13,
    isFeatured: false,
  },
  {
    _id: 'fb-sale-14',
    slug: 'kia-sorento-signature-2022',
    title: 'Kia Sorento Signature AWD 2022',
    brand: 'Kia',
    model: 'Sorento',
    year: 2022,
    condition: 'used',
    color: 'Steel Grey',
    price: 6800000,
    salePrice: 6800000,
    mileage: 18000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    seats: 7,
    doors: 5,
    location: 'Uttara',
    description: 'Flagship 7-seater Korean SUV, Bose premium sound, 360-degree blind spot camera, dual panoramic roof.',
    coverImage: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'sale',
    status: 'published',
    rating: 4.8,
    totalReviews: 9,
    isFeatured: false,
  },
  {
    _id: 'fb-sale-15',
    slug: 'mazda-cx5-grand-touring-2021',
    title: 'Mazda CX-5 Grand Touring 2021',
    brand: 'Mazda',
    model: 'CX-5',
    year: 2021,
    condition: 'used',
    color: 'Soul Red Crystal',
    price: 4300000,
    salePrice: 4300000,
    mileage: 31000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'SUV',
    seats: 5,
    doors: 5,
    location: 'Dhaka',
    description: 'Iconic Soul Red Crystal paint, Bose 10-speaker system, head-up display, i-Activsense safety suite.',
    coverImage: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'sale',
    status: 'published',
    rating: 4.9,
    totalReviews: 12,
    isFeatured: false,
  },
  {
    _id: 'fb-sale-16',
    slug: 'toyota-rav4-hybrid-limited-2022',
    title: 'Toyota RAV4 Hybrid Limited AWD 2022',
    brand: 'Toyota',
    model: 'RAV4',
    year: 2022,
    condition: 'certified',
    color: 'Blueprint Blue',
    price: 6100000,
    salePrice: 6100000,
    mileage: 21000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'SUV',
    seats: 5,
    doors: 5,
    location: 'Sylhet',
    description: 'Top-tier Limited trim with electronic AWD, heated/ventilated front seats, digital rearview mirror.',
    coverImage: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'sale',
    status: 'published',
    rating: 4.8,
    totalReviews: 14,
    isFeatured: false,
  },
  {
    _id: 'fb-sale-17',
    slug: 'lexus-rx350-f-sport-2021',
    title: 'Lexus RX 350 F-Sport AWD 2021',
    brand: 'Lexus',
    model: 'RX 350',
    year: 2021,
    condition: 'used',
    color: 'Sonic Titanium',
    price: 13500000,
    salePrice: 13500000,
    mileage: 27000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'SUV',
    seats: 5,
    doors: 5,
    location: 'Gulshan',
    description: 'F-Sport performance package, Mark Levinson 15-speaker audio, adaptive variable suspension, red leather.',
    coverImage: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'sale',
    status: 'published',
    rating: 5.0,
    totalReviews: 17,
    isFeatured: true,
  },
  {
    _id: 'fb-sale-18',
    slug: 'hyundai-santa-fe-turbo-2022',
    title: 'Hyundai Santa Fe 2.5T Calligraphy 2022',
    brand: 'Hyundai',
    model: 'Santa Fe',
    year: 2022,
    condition: 'used',
    color: 'Hampton Grey',
    price: 6500000,
    salePrice: 6500000,
    mileage: 22000,
    fuelType: 'Petrol',
    transmission: 'Dual-Clutch',
    bodyType: 'SUV',
    seats: 7,
    doors: 5,
    location: 'Chattogram',
    description: 'Calligraphy top-grade package, 20-inch alloy rims, quilted Nappa leather, Harman Kardon sound.',
    coverImage: 'https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'sale',
    status: 'published',
    rating: 4.9,
    totalReviews: 10,
    isFeatured: false,
  },
  {
    _id: 'fb-sale-19',
    slug: 'volkswagen-tiguan-allspace-2022',
    title: 'Volkswagen Tiguan Allspace R-Line 2022',
    brand: 'Volkswagen',
    model: 'Tiguan',
    year: 2022,
    condition: 'used',
    color: 'Deep Black Pearl',
    price: 5800000,
    salePrice: 5800000,
    mileage: 25000,
    fuelType: 'Petrol',
    transmission: 'Dual-Clutch',
    bodyType: 'SUV',
    seats: 7,
    doors: 5,
    location: 'Dhaka',
    description: '7-seater German engineering, 4MOTION all-wheel drive, Digital Cockpit Pro, IQ.LIGHT LED matrix.',
    coverImage: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'sale',
    status: 'published',
    rating: 4.8,
    totalReviews: 8,
    isFeatured: false,
  },
  {
    _id: 'fb-sale-20',
    slug: 'toyota-yaris-ativ-2022',
    title: 'Toyota Yaris ATIV Premium 2022',
    brand: 'Toyota',
    model: 'Yaris',
    year: 2022,
    condition: 'used',
    color: 'Red Mica Metallic',
    price: 2450000,
    salePrice: 2450000,
    mileage: 28000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    seats: 5,
    doors: 4,
    location: 'Dhaka',
    description: 'Affordable compact sedan, pristine fuel efficiency, 6 airbags, push start, touchscreen with Apple CarPlay.',
    coverImage: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'sale',
    status: 'published',
    rating: 4.7,
    totalReviews: 19,
    isFeatured: false,
  },

  // ── 20 FOR RENT CARS ────────────────────────────────────────────────────────
  {
    _id: 'fb-rent-1',
    slug: 'toyota-noah-hybrid-van-2022',
    title: 'Toyota Noah Hybrid Luxury Van 2022',
    brand: 'Toyota',
    model: 'Noah',
    year: 2022,
    condition: 'used',
    color: 'Pearl White',
    rentalPrice: 5500,
    price: 5500,
    mileage: 32000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'Van / Minivan',
    seats: 7,
    doors: 5,
    location: 'Dhaka',
    description: 'Spacious 7-seater passenger van with captain seats, dual power sliding doors, ideal for family and tours.',
    coverImage: 'https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'rent',
    status: 'published',
    rating: 5.0,
    totalReviews: 24,
    isFeatured: true,
  },
  {
    _id: 'fb-rent-2',
    slug: 'toyota-hiace-super-gl-2021',
    title: 'Toyota HiAce Super GL VIP 2021',
    brand: 'Toyota',
    model: 'HiAce',
    year: 2021,
    condition: 'used',
    color: 'Metallic Silver',
    rentalPrice: 7500,
    price: 7500,
    mileage: 48000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'Van / Minivan',
    seats: 12,
    doors: 5,
    location: 'Uttara',
    description: '12-seat executive passenger van, dual air conditioning, reclining luxury seats, perfect for corporate events.',
    coverImage: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'rent',
    status: 'published',
    rating: 4.9,
    totalReviews: 31,
    isFeatured: true,
  },
  {
    _id: 'fb-rent-3',
    slug: 'toyota-allion-g-plus-2020',
    title: 'Toyota Allion G Plus 2020',
    brand: 'Toyota',
    model: 'Allion',
    year: 2020,
    condition: 'used',
    color: 'Wine Red',
    rentalPrice: 3800,
    price: 3800,
    mileage: 45000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    seats: 5,
    doors: 4,
    location: 'Dhanmondi',
    description: 'Chauffeur driven comfortable city sedan. Chilled AC, smooth ride, professional verified driver included.',
    coverImage: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'rent',
    status: 'published',
    rating: 4.8,
    totalReviews: 18,
    isFeatured: false,
  },
  {
    _id: 'fb-rent-4',
    slug: 'mitsubishi-pajero-sport-2021',
    title: 'Mitsubishi Pajero Sport 4x4 2021',
    brand: 'Mitsubishi',
    model: 'Pajero Sport',
    year: 2021,
    condition: 'used',
    color: 'Graphite Gray',
    rentalPrice: 11000,
    price: 11000,
    mileage: 39000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    seats: 7,
    doors: 5,
    location: 'Gulshan',
    description: 'Heavy duty 4x4 turbo diesel SUV. Ready for highway tours, Cox’s Bazar or Sylhet trips. High ground clearance.',
    coverImage: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'rent',
    status: 'published',
    rating: 4.9,
    totalReviews: 15,
    isFeatured: true,
  },
  {
    _id: 'fb-rent-5',
    slug: 'kia-sportage-gt-line-2022',
    title: 'Kia Sportage GT-Line 2022',
    brand: 'Kia',
    model: 'Sportage',
    year: 2022,
    condition: 'used',
    color: 'Snow White',
    rentalPrice: 6500,
    price: 6500,
    mileage: 26000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'SUV',
    seats: 5,
    doors: 5,
    location: 'Banani',
    description: 'Modern sporty crossover, panoramic sunroof, premium Harman Kardon audio, heated and cooled seats.',
    coverImage: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'rent',
    status: 'published',
    rating: 4.8,
    totalReviews: 19,
    isFeatured: false,
  },
  {
    _id: 'fb-rent-6',
    slug: 'range-rover-evoque-2022',
    title: 'Range Rover Evoque R-Dynamic 2022',
    brand: 'Land Rover',
    model: 'Range Rover Evoque',
    year: 2022,
    condition: 'used',
    color: 'Carpathian Grey',
    rentalPrice: 18000,
    price: 18000,
    mileage: 17000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'SUV',
    seats: 5,
    doors: 5,
    location: 'Gulshan',
    description: 'VIP Wedding and Corporate rental vehicle. High luxury interior, panoramic roof, Meridian surround sound.',
    coverImage: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'rent',
    status: 'published',
    rating: 5.0,
    totalReviews: 28,
    isFeatured: true,
  },
  {
    _id: 'fb-rent-7',
    slug: 'toyota-corolla-cross-hybrid-2022',
    title: 'Toyota Corolla Cross Hybrid 2022',
    brand: 'Toyota',
    model: 'Corolla Cross',
    year: 2022,
    condition: 'used',
    color: 'Attitude Black',
    rentalPrice: 5000,
    price: 5000,
    mileage: 22000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'SUV',
    seats: 5,
    doors: 5,
    location: 'Sylhet',
    description: 'Fuel efficient hybrid SUV, super smooth suspension, Toyota Safety Sense, Apple CarPlay and Android Auto.',
    coverImage: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'rent',
    status: 'published',
    rating: 4.9,
    totalReviews: 16,
    isFeatured: false,
  },
  {
    _id: 'fb-rent-8',
    slug: 'bmw-5-series-520i-2022',
    title: 'BMW 5 Series 520i Luxury Line 2022',
    brand: 'BMW',
    model: '5 Series',
    year: 2022,
    condition: 'used',
    color: 'Bernina Grey',
    rentalPrice: 15000,
    price: 15000,
    mileage: 19000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    seats: 5,
    doors: 4,
    location: 'Dhaka',
    description: 'Executive sedan for VVIP protocol, weddings, and executive delegations. Chauffeur included upon request.',
    coverImage: 'https://images.unsplash.com/photo-1523983388277-336a66bf9bcd?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1523983388277-336a66bf9bcd?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'rent',
    status: 'published',
    rating: 5.0,
    totalReviews: 22,
    isFeatured: true,
  },
  {
    _id: 'fb-rent-9',
    slug: 'hyundai-santa-fe-awd-2022',
    title: 'Hyundai Santa Fe Calligraphy AWD 2022',
    brand: 'Hyundai',
    model: 'Santa Fe',
    year: 2022,
    condition: 'used',
    color: 'Forest Green',
    rentalPrice: 9500,
    price: 9500,
    mileage: 28000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    seats: 7,
    doors: 5,
    location: 'Gulshan',
    description: '7-passenger premium family SUV with quilted Nappa leather, 360-degree monitor, remote smart park assist.',
    coverImage: 'https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'rent',
    status: 'published',
    rating: 4.9,
    totalReviews: 20,
    isFeatured: false,
  },
  {
    _id: 'fb-rent-10',
    slug: 'toyota-axio-hybrid-2021',
    title: 'Toyota Corolla Axio Hybrid 2021',
    brand: 'Toyota',
    model: 'Axio',
    year: 2021,
    condition: 'used',
    color: 'Super White',
    rentalPrice: 3200,
    price: 3200,
    mileage: 52000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    seats: 5,
    doors: 4,
    location: 'Dhaka',
    description: 'Affordable daily rental car with exceptional fuel efficiency. Reliable, clean, perfect for daily commuting in Dhaka.',
    coverImage: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'rent',
    status: 'published',
    rating: 4.7,
    totalReviews: 35,
    isFeatured: false,
  },
  {
    _id: 'fb-rent-11',
    slug: 'toyota-land-cruiser-v8-2021',
    title: 'Toyota Land Cruiser V8 VIP 2021',
    brand: 'Toyota',
    model: 'Land Cruiser',
    year: 2021,
    condition: 'used',
    color: 'Pearl White',
    rentalPrice: 22000,
    price: 22000,
    mileage: 35000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    seats: 7,
    doors: 5,
    location: 'Gulshan',
    description: 'VVIP Armored protocol package, chiller box, rear seat entertainment, chauffeur in executive protocol uniform.',
    coverImage: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'rent',
    status: 'published',
    rating: 5.0,
    totalReviews: 29,
    isFeatured: true,
  },
  {
    _id: 'fb-rent-12',
    slug: 'mercedes-benz-e200-2022',
    title: 'Mercedes-Benz E-Class E200 2022',
    brand: 'Mercedes-Benz',
    model: 'E-Class',
    year: 2022,
    condition: 'used',
    color: 'Iridium Silver',
    rentalPrice: 16000,
    price: 16000,
    mileage: 21000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    seats: 5,
    doors: 4,
    location: 'Banani',
    description: 'Executive wedding and diplomatic delegations car. Ambient lighting 64 colors, soft-close doors, high comfort.',
    coverImage: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'rent',
    status: 'published',
    rating: 4.9,
    totalReviews: 26,
    isFeatured: true,
  },
  {
    _id: 'fb-rent-13',
    slug: 'audi-a6-matrix-2021',
    title: 'Audi A6 45 TFSI Quattro 2021',
    brand: 'Audi',
    model: 'A6',
    year: 2021,
    condition: 'used',
    color: 'Mythos Black',
    rentalPrice: 14000,
    price: 14000,
    mileage: 29000,
    fuelType: 'Petrol',
    transmission: 'Dual-Clutch',
    bodyType: 'Sedan',
    seats: 5,
    doors: 4,
    location: 'Uttara',
    description: 'All-wheel Quattro grip, dual touchscreen MMI, Bang & Olufsen audio, executive airport transfer specialist.',
    coverImage: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'rent',
    status: 'published',
    rating: 4.8,
    totalReviews: 17,
    isFeatured: false,
  },
  {
    _id: 'fb-rent-14',
    slug: 'toyota-alphard-executive-2022',
    title: 'Toyota Alphard Executive Lounge 2022',
    brand: 'Toyota',
    model: 'Alphard',
    year: 2022,
    condition: 'used',
    color: 'Pearl White',
    rentalPrice: 20000,
    price: 20000,
    mileage: 18000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'Van / Minivan',
    seats: 7,
    doors: 5,
    location: 'Gulshan',
    description: 'First class airline style Ottoman reclining seats, ambient roof lighting, power shades, VVIP luxury van.',
    coverImage: 'https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'rent',
    status: 'published',
    rating: 5.0,
    totalReviews: 33,
    isFeatured: true,
  },
  {
    _id: 'fb-rent-15',
    slug: 'hyundai-staria-vip-2022',
    title: 'Hyundai Staria Lounge 7-Seater 2022',
    brand: 'Hyundai',
    model: 'Staria',
    year: 2022,
    condition: 'used',
    color: 'Abyss Black',
    rentalPrice: 9000,
    price: 9000,
    mileage: 24000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'Van / Minivan',
    seats: 7,
    doors: 5,
    location: 'Dhanmondi',
    description: 'Futuristic exterior styling, panoramic glass windows, relaxation captain seats, spacious family road tripper.',
    coverImage: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'rent',
    status: 'published',
    rating: 4.9,
    totalReviews: 21,
    isFeatured: false,
  },
  {
    _id: 'fb-rent-16',
    slug: 'toyota-fortuner-sigma4-2021',
    title: 'Toyota Fortuner Sigma 4 4x4 2021',
    brand: 'Toyota',
    model: 'Fortuner',
    year: 2021,
    condition: 'used',
    color: 'Attitude Black',
    rentalPrice: 12000,
    price: 12000,
    mileage: 36000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    seats: 7,
    doors: 5,
    location: 'Chattogram',
    description: 'Tough 4x4 diesel SUV for hilly tracks, Sajek Valley or Bandarban tours. High stance and rugged suspension.',
    coverImage: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'rent',
    status: 'published',
    rating: 4.9,
    totalReviews: 19,
    isFeatured: true,
  },
  {
    _id: 'fb-rent-17',
    slug: 'honda-vezel-rs-hybrid-2021',
    title: 'Honda Vezel RS Hybrid 2021',
    brand: 'Honda',
    model: 'Vezel',
    year: 2021,
    condition: 'used',
    color: 'Premium Crystal Red',
    rentalPrice: 4500,
    price: 4500,
    mileage: 38000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'SUV',
    seats: 5,
    doors: 5,
    location: 'Dhaka',
    description: 'Sporty RS package crossover. Sport alloy rims, paddle shifters, Honda Sensing, very fuel efficient.',
    coverImage: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'rent',
    status: 'published',
    rating: 4.8,
    totalReviews: 25,
    isFeatured: false,
  },
  {
    _id: 'fb-rent-18',
    slug: 'nissan-x-trail-hybrid-rent-2021',
    title: 'Nissan X-Trail Hybrid 4WD 2021',
    brand: 'Nissan',
    model: 'X-Trail',
    year: 2021,
    condition: 'used',
    color: 'Pearl White',
    rentalPrice: 5800,
    price: 5800,
    mileage: 41000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'SUV',
    seats: 5,
    doors: 5,
    location: 'Sylhet',
    description: 'Comfortable family SUV with panoramic sunroof, 4WD traction for tea garden tours, leather interior.',
    coverImage: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'rent',
    status: 'published',
    rating: 4.8,
    totalReviews: 14,
    isFeatured: false,
  },
  {
    _id: 'fb-rent-19',
    slug: 'toyota-yaris-cross-hybrid-2022',
    title: 'Toyota Yaris Cross Hybrid Z 2022',
    brand: 'Toyota',
    model: 'Yaris Cross',
    year: 2022,
    condition: 'used',
    color: 'Brass Gold Metallic',
    rentalPrice: 4200,
    price: 4200,
    mileage: 26000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'SUV',
    seats: 5,
    doors: 5,
    location: 'Dhaka',
    description: 'Compact hybrid crossover, easy to drive in narrow city lanes, excellent fuel economy of 28 km/L.',
    coverImage: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'rent',
    status: 'published',
    rating: 4.8,
    totalReviews: 18,
    isFeatured: false,
  },
  {
    _id: 'fb-rent-20',
    slug: 'kia-carnival-limousine-2022',
    title: 'Kia Carnival Limousine 7-Seater 2022',
    brand: 'Kia',
    model: 'Carnival',
    year: 2022,
    condition: 'used',
    color: 'Panthera Metal',
    rentalPrice: 11000,
    price: 11000,
    mileage: 23000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'Van / Minivan',
    seats: 7,
    doors: 5,
    location: 'Gulshan',
    description: 'VIP Multi Purpose Vehicle with dual sunroofs, VIP lounge seating with leg support, Bose audio.',
    coverImage: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80'],
    listingType: 'rent',
    status: 'published',
    rating: 5.0,
    totalReviews: 27,
    isFeatured: true,
  },
];

export const FALLBACK_20_CARS: ICar[] = RAW_CARS.map((car) => ({
  features: car.features || ['Air Conditioning', 'Power Steering', 'ABS Brakes'],
  amenities: car.amenities || ['Bluetooth', 'Audio System', 'Central Locking'],
  images: car.images || [car.coverImage],
  status: 'published' as const,
  rating: car.rating || 4.9,
  totalReviews: car.totalReviews || 12,
  viewsCount: 0,
  ...car,
}));
